steps:
  # Build backend
  - name: gcr.io/theta-mile-271809/lokaler.kaufen.build-container
    id: "build-backend"
    entrypoint: gradle
    args: ["--no-daemon", "--gradle-user-home", "/gradle-cache", "-i", "-u", "gradle", "build"]
    dir: backend
    waitFor: ["-"]
  # Analyze backend code quality
  - name: gcr.io/theta-mile-271809/lokaler.kaufen.build-container
    entrypoint: gradle
    args: ["--no-daemon", "--gradle-user-home", "/gradle-cache", "-i", "-u", "gradle", "clean", "test", "sonarqube"]
    dir: backend
    secretEnv: ["SONAR_TOKEN"]
    waitFor: ["build-backend"]
  # Build Docker image (frontend & backend)
  - name: gcr.io/cloud-builders/docker
    id: "build-image"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lokaler.kaufen", "."]
    waitFor: ["-"]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args: ["push", "gcr.io/$PROJECT_ID/lokaler.kaufen"]
    waitFor: ["build-image"]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'lokaler-kaufen-srv', '--image', 'gcr.io/$PROJECT_ID/lokaler.kaufen', '--region', 'europe-west4', '--platform', 'managed', '--allow-unauthenticated']
    waitFor: ["push-image"]

# Increase timeout to 15 minutes 
timeout: 900s

# Use vm with more CPU power
options:
  machineType: "N1_HIGHCPU_8"

secrets:
  - kmsKeyName: projects/theta-mile-271809/locations/global/keyRings/lokalerkaufen/cryptoKeys/CLOUD_BUILD_KEY
    secretEnv:
      SONAR_TOKEN: CiQA/jo+T7PGbQt72sqrRL5dVspyk3/vXr2HxoE406bZRwJtNEcSUQAOg7t2m3AOYeaF1tFS/Fp8EI+WHcHQ7cg46KyVqoO8j0o146ak/ec7yt5OnRBXkYO028xvyfMz2JWifTJRO6PHb3MMHh3Mpqci0rfAzn49aQ==