spring.datasource:
  url: "jdbc:postgresql://localhost:5432/postgres"
  username: "postgres"
  password: "password"
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: false

mercury:
  tokens:
    shopJwtSecret: "u2WXgWEWhyop+qtpiH5jhQmDN+PVRbazKPNuseI0dmE=" # openssl rand -base64 32
    adminJwtSecret: "QXOm/a5//OFtmciYomnixCTDCzNUQFWNAiT3eGBOfhQ=" # openssl rand -base64 32
    shopCreationJwtSecret: "8aaM086u9cpaNp8fMKURLOdpTEJYPqFy/xrN3M5ynT4=" # openssl rand -base64 32
    passwordResetJwtSecret: "71GRYLeFT2QzI/nq+g4UMk1hQ7Q+X2SvCU3ge5Nkpd8=" # openssl rand -base64 32
  email:
    use-dummy: true # Set this to false to send real emails
    from: "Lokaler.kaufen <info@lokaler.kaufen>"
    creationLinkTemplate: "http://localhost:4200/#/create-shop?token={{ token }}"
    shopPasswordResetLinkTemplate: "http://localhost:4200/#/reset-shop-password?token={{ token }}"
  features:
    enableDebugDataCreation: true
    enableShopsOnCreation: true

spring.mail:
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  properties:
    mail.smtp.starttls.enable: true
