# Overriden to include the traceId in the log output
logging.pattern.console: "%date{yyyy-MM-dd HH:mm:ss.SSSZ} %clr(%5level) [%mdc{traceId:-?}] ${PID:- } --- [%15.15t] %-40.40logger{39} : %message%n%wEx"
logging.level:
  de.qaware.mercury: DEBUG

spring.datasource:
  url: "invalid-jdbc-url" # Invalid url is on purpose so that spring breaks when no database is configured
  hikari:
    auto-commit: false
    connection-timeout: 10000 # ms
    maximum-pool-size: 10 # Before fiddling with this value, read this: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

spring.jpa:
  hibernate.ddl-auto: validate
  open-in-view: false
  database-platform: org.hibernate.dialect.PostgreSQL10Dialect

mercury:
  sharing:
    shopDetailLinkTemplate: "${variables.domain}/#/shops/{{ id }}"
    shopShareLinkTemplate: "${variables.domain}/bei/{{ slug }}"
  frontend:
    enable-caching: true
  images:
    devControllerEnabled: false
    publicUrlTemplate: ""
    storageLocation: ""
    size: 250 # pixel
    quality: 90
  cookies:
    secure: true
  tokens:
    masterKey: "fZZP2re13vX7Q6xEWJDlAyYdzwtmZTmSEvjafucWlYg=" # Must be Base64, generated with openssl rand -base64 32
  email:
    useDummy: true # Set this to false to send real emails
    from: "Lokaler.kaufen <info@lokaler.kaufen>"
    creationLinkTemplate: "${variables.domain}/#/create-shop?token={{ token }}"
    shopPasswordResetLinkTemplate: "${variables.domain}/#/reset-shop-password?token={{ token }}"
    reservationCancellationLinkTemplate: "${variables.domain}/#/cancel-reservation?token={{ token }}"
    adminUiLink: "${variables.domain}/#/admin/overview"
  features:
    enableDebugDataCreation: false
    approveShopsOnCreation: false
  cleanup-job:
    reservation:
      cron: "0 0 2 * * *" # Every night at 2am

spring.mail:
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  properties:
    mail.smtp.starttls.enable: true

spring.servlet:
  # Enable multipart uploads
  multipart:
    enabled: true
    max-file-size: 5MB
    max-request-size: 6MB

variables:
  domain: "http://localhost:4200"
