spring.datasource:
  url: "jdbc:postgresql://localhost:5432/postgres"
  username: "postgres"
  password: "password"
  hikari:
    auto-commit: false
    connection-timeout: 10000 # ms
    maximum-pool-size: 10 # Before fiddling with this value, read this: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: false

mercury:
  tokens:
    shopJwtSecret: "u2WXgWEWhyop+qtpiH5jhQmDN+PVRbazKPNuseI0dmE=" # openssl rand -base64 32
    adminJwtSecret: "QXOm/a5//OFtmciYomnixCTDCzNUQFWNAiT3eGBOfhQ=" # openssl rand -base64 32
    shopCreationJwtSecret: "8aaM086u9cpaNp8fMKURLOdpTEJYPqFy/xrN3M5ynT4=" # openssl rand -base64 32
    passwordResetJwtSecret: "71GRYLeFT2QzI/nq+g4UMk1hQ7Q+X2SvCU3ge5Nkpd8=" # openssl rand -base64 32
    reservationCancellationJwtSecret: "aOAUO26KvMsqgb+lRl2o1dQFziRMBnQI9mw5rMxabcE" # openssl rand -base64 32
  email:
    use-dummy: true # Set this to false to send real emails
    from: "Lokaler.kaufen <info@lokaler.kaufen>"
    creationLinkTemplate: "${variables.domain}/#/create-shop?token={{ token }}"
    shopPasswordResetLinkTemplate: "${variables.domain}/#/reset-shop-password?token={{ token }}"
    reservationCancellationLinkTemplate: "${variables.domain}/#/cancel-reservation?token={{ token }}"
  features:
    enableDebugDataCreation: true
    approveShopsOnCreation: true

spring.mail:
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  properties:
    mail.smtp.starttls.enable: true

variables:
  domain: "http://localhost:4200"
