spring.jpa.show-sql: true
spring.datasource:
  url: "jdbc:postgresql://localhost:5432/postgres"
  username: "postgres"
  password: "password"

mercury:
  images:
    publicUrlTemplate: "http://localhost:8080/dev/image/{{ filename }}"
    storageLocation: "/tmp/mercury-images"
    devControllerEnabled: true
    size: 500 # pixel
    quality: 90
  cookies:
    secure: false
  email:
    use-dummy: true # Set this to false to send real emails
  features:
    enableDebugDataCreation: true
    approveShopsOnCreation: true
  cleanup-job:
    reservation:
      cron: "0 * * * * *"

variables:
  domain: "http://localhost:4200"
